In [1]:
import numpy as np

In [2]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [3]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [4]:
a_list[3]

4

In [5]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [6]:
k_krotka[4]

5

In [9]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [8]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [10]:
n_array = np.array(a_list) # wektor numpy

In [11]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [12]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [13]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [18]:
studenci_slownik["Zosia"]

22

In [19]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
Cuthulu
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)
Cuthulu


In [20]:
for elementy in studenci_slownik.items():
    print(elementy)

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')
('Cuthulu', -1000000)


In [21]:
for elementy in studenci_slownik.values():
    print(elementy)

123
3
5
22
[2, 21]
Krotka
-1000000


In [22]:
studenci_slownik["Cuthulu"]= -1000000

In [23]:
studenci_slownik

{123: 123,
 'Igor': 3,
 'Frankek': 5,
 'Zosia': 22,
 'Julia': [2, 21],
 (1, 2): 'Krotka',
 'Cuthulu': -1000000}

In [24]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [25]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [26]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [27]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [28]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [25]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [107]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [29]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [30]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [31]:
pio_zajecia.ile_zajec

4

In [32]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [33]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [34]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [35]:
pio_zajecia.ile_mispow()

4

In [36]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [85]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [105]:
print(pio_zajecia.ile_zajec)

5


In [108]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [109]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [112]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [113]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [114]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


## challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
Zawartość klasy:
- Funkcja inicalizująca w klasie sprawdza czy numer jest poprawny czy nie i wyświetlany odpowiedni komunikat. Weryfikacja realizowana jest na podstawie sprawdzenia długości znaków. Prawdziwą weryfikację należałoby wykonać przy użyciu RegEx
- funckja województwo odpwoiedzialne jest za wyświetelnie nazwy województwa w przypadku gdy numer znajduje się w słowniku. Z racji, że numerów jest ok 49 zostały wpisane 3 przykładowe w celu sprawdzenia działania. Z numeru podanego przy wyzwalaniu klasy brane są pierwsze dwie cyfry i porównywane z w.w. zbiorem. Jeśli nie znajdzie się w zbiorze wyświetlany jest komunikat o numerze komórkowym. 
- funkcja repr odpowiedzialna jest za zwracaną wartość do printa. Na początku jest lista zawierająca kolejne cyfry zapisane słownie, oraz listę do przechowywania tworzonego ciągu cyfr. Następnie w pętli dla każej z cyfr odpowiednik tekstowy dopisywany jest do tej listy i finalnie zwracany jako jeden ciąg. 

 

 

In [20]:
class NumerTelefonu():

    def __init__(self,numer):
        self.numer_telefonu = numer
        if len(self.numer_telefonu) == 9:                                   # Sprawdzam długość i informuje czy dobry czy zły
            print("Numer poprawny")
        else:
            print("numer niepoprawny")

    def wojewodztwo(self):
        numer_kierunkowy = self.numer_telefonu[0]+self.numer_telefonu[1]    # Tworze zmienną z numerem kierunkowym
        numery_kierunkowe = {"42":"Lodz","12":"Kraków","94":"Koszalin"}     # Tablica z kierunkowymi
        try:                                                                # próbuję przypisać kierunkowy do typu numery, jeśli się nie uda to przypisuje, że to komórkowy
            typ_numeru = numery_kierunkowe[numer_kierunkowy]
        except KeyError:
            typ_numeru = "Komorkowy"
        return typ_numeru


    def __repr__(self):
        cyfry = ["zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć"]
        telefon_do_tekstu = ""
        for cyfra in self.numer_telefonu:                                   # w kolejnych iteracjach pętli dla kolejnej litery doklejam słowny odpowiednik
            telefon_do_tekstu = telefon_do_tekstu + " " + cyfry[int(cyfra)]
        return telefon_do_tekstu                                            # i finalnie go wyświetlam

In [21]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
# >>> "prawidlowy numer"


Numer poprawny


In [22]:

numer_lodz.wojewodztwo()
# >>> "Lodz"


'Lodz'

In [23]:

print(numer_lodz)
# >>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

 cztery dwa sześć osiem siedem siedem osiem sześć osiem
